name: TestPlugin
version: '${project.version}'
main: com.gmail.subnokoii.testplugin.TestPlugin
api-version: '1.20'
commands:
  foo:
    description: '文字列「foo!」を表示します'
    usage: '/<command>'
  lobby:
    description: '実行者・もしくは指定のプレイヤーをロビーサーバーに転送します'
    usage: '/<command> [<player>]'
  log:
    description: 'ログを管理します'
  tools:
    description: 'プラグイン製のツールを取り出すためのUIを表示します'
  test:
    description: 'デバッグ用コマンドのため機能が頻繁に追加・削除・変更されます'
